annotations:
    truecharts.org/SCALE-support: "true"
    truecharts.org/category: productivity
apiVersion: v2
appVersion: 5.1.1
dependencies:
    - name: common
      repository: https://library-charts.truecharts.org
      version: 14.3.5
description: Redmine is a flexible project management web application written using Ruby on Rails framework.
home: https://truecharts.org/charts/stable/redmine
icon: https://truecharts.org/img/hotlink-ok/chart-icons/redmine.png
keywords:
    - project
    - management
    - time
    - tracking
    - ticket
kubeVersion: '>=1.16.0-0'
maintainers:
    - email: info@truecharts.org
      name: TrueCharts
      url: https://truecharts.org
name: redmine
sources:
    - https://github.com/truecharts/charts/tree/master/charts/stable/redmine
    - https://github.com/redmine/redmine
type: application
version: 8.2.1
