annotations:
    max_scale_version: 23.10.1
    min_scale_version: 22.12.4
    truecharts.org/SCALE-support: "true"
    truecharts.org/category: incubator
apiVersion: v2
appVersion: 8.0.34
dependencies:
    - name: common
      repository: https://library-charts.truecharts.org
      version: 14.3.5
deprecated: false
description: MySQL Workbench is a unified visual tool for database architects, developers and DBAs.
home: https://truecharts.org/charts/stable/mysql-workbench
icon: https://truecharts.org/img/hotlink-ok/chart-icons/mysql-workbench.png
keywords:
    - mysql-workbench
kubeVersion: '>=1.16.0-0'
maintainers:
    - email: info@truecharts.org
      name: TrueCharts
      url: https://truecharts.org
name: mysql-workbench
sources:
    - https://github.com/truecharts/charts/tree/master/charts/stable/mysql-workbench
type: application
version: 6.0.24
