annotations:
    max_scale_version: 23.10.1
    min_scale_version: 22.12.4
    truecharts.org/SCALE-support: "false"
    truecharts.org/category: iot
apiVersion: v2
appVersion: latest
dependencies:
    - name: common
      repository: https://library-charts.truecharts.org
      version: 11.1.2
deprecated: false
description: A free and non-commercial open-source operating system alternative for running a cloud-free smart-home IoT.
home: https://truecharts.org/charts/incubator/raspberrymatic
icon: https://truecharts.org/img/hotlink-ok/chart-icons/raspberrymatic.png
keywords:
    - raspberrymatic
    - iot
kubeVersion: '>=1.16.0-0'
maintainers:
    - email: info@truecharts.org
      name: TrueCharts
      url: https://truecharts.org
name: raspberrymatic
sources:
    - https://github.com/truecharts/charts/tree/master/charts/incubator/raspberrymatic
    - https://github.com/jens-maus/RaspberryMatic
    - https://github.com/jens-maus/RaspberryMatic/pkgs/container/raspberrymatic
type: application
version: 2.0.12
