annotations:
    max_scale_version: 23.10.1
    min_scale_version: 22.12.4
    truecharts.org/SCALE-support: "true"
    truecharts.org/category: download-tools
apiVersion: v2
appVersion: 4.0.4
dependencies:
    - name: common
      repository: https://library-charts.truecharts.org
      version: 14.3.5
deprecated: false
description: fast, easy, and free BitTorrent client.
home: https://truecharts.org/charts/stable/transmission
icon: https://truecharts.org/img/hotlink-ok/chart-icons/transmission.png
keywords:
    - transmission
    - torrent
    - usenet
kubeVersion: '>=1.16.0-0'
maintainers:
    - email: info@truecharts.org
      name: TrueCharts
      url: https://truecharts.org
name: transmission
sources:
    - https://github.com/truecharts/charts/tree/master/charts/stable/transmission
    - https://github.com/transmission/transmission
type: application
version: 17.0.14
