annotations:
    max_scale_version: 23.10.1
    min_scale_version: 22.12.4
    truecharts.org/SCALE-support: "true"
    truecharts.org/category: media
apiVersion: v2
appVersion: 1.8.14
dependencies:
    - name: common
      repository: https://library-charts.truecharts.org
      version: 14.3.5
description: A real-time collaborative editor scalable to thousands of simultaneous real time users.
home: https://truecharts.org/charts/stable/etherpad
icon: https://truecharts.org/img/hotlink-ok/chart-icons/etherpad.png
keywords:
    - etherpad
    - editor
    - notepad
    - pad
kubeVersion: '>=1.16.0-0'
maintainers:
    - email: info@truecharts.org
      name: TrueCharts
      url: https://truecharts.org
name: etherpad
sources:
    - https://github.com/truecharts/charts/tree/master/charts/stable/etherpad
    - https://etherpad.org/
    - https://github.com/ether/etherpad-lite
type: application
version: 13.0.9
