annotations:
    max_scale_version: 23.10.1
    min_scale_version: 22.12.4
    truecharts.org/SCALE-support: "true"
    truecharts.org/category: media
apiVersion: v2
appVersion: 1.5.4
dependencies:
    - name: common
      repository: https://library-charts.truecharts.org
      version: 14.3.5
description: Spotweb is a decentralized usenet community based on the Spotnet protocol.
home: https://truecharts.org/charts/stable/spotweb
icon: https://truecharts.org/img/hotlink-ok/chart-icons/spotweb.png
keywords:
    - usenet
    - spotweb
    - spotnet
kubeVersion: '>=1.16.0-0'
maintainers:
    - email: info@truecharts.org
      name: TrueCharts
      url: https://truecharts.org
name: spotweb
sources:
    - https://github.com/truecharts/charts/tree/master/charts/stable/spotweb
    - https://github.com/spotweb/spotweb
    - https://github.com/joachimbaten/spotweb-docker
type: application
version: 9.0.9
