annotations:
    max_scale_version: 23.10.1
    min_scale_version: 22.12.4
    truecharts.org/SCALE-support: "true"
    truecharts.org/category: media
apiVersion: v2
appVersion: 1.2.8
dependencies:
    - name: common
      repository: https://library-charts.truecharts.org
      version: 11.1.2
deprecated: false
description: Share your game clips, videos, or other media via unique links.
home: https://truecharts.org/charts/incubator/fireshare
icon: https://truecharts.org/img/hotlink-ok/chart-icons/fireshare.png
keywords:
    - fireshare
kubeVersion: '>=1.16.0-0'
maintainers:
    - email: info@truecharts.org
      name: TrueCharts
      url: https://truecharts.org
name: fireshare
sources:
    - https://github.com/truecharts/charts/tree/master/charts/incubator/fireshare
    - https://github.com/ShaneIsrael/fireshare
type: application
version: 2.0.11
