annotations:
    max_scale_version: 23.10.1
    min_scale_version: 22.12.4
    truecharts.org/SCALE-support: "true"
    truecharts.org/category: media
apiVersion: v2
appVersion: "057352e8"
dependencies:
    - name: common
      repository: https://library-charts.truecharts.org
      version: 14.3.5
description: A lightweight portal to view & manage your HTPC apps without having to run anything more than a PHP enabled webserver
home: https://truecharts.org/charts/stable/muximux
icon: https://truecharts.org/img/hotlink-ok/chart-icons/muximux.png
keywords:
    - muximux
    - htpc
    - manage
    - portal
kubeVersion: '>=1.16.0-0'
maintainers:
    - email: info@truecharts.org
      name: TrueCharts
      url: https://truecharts.org
name: muximux
sources:
    - https://github.com/truecharts/charts/tree/master/charts/stable/muximux
    - https://github.com/linuxserver/docker-muximux
    - https://github.com/mescon/Muximux
type: application
version: 7.0.9
