annotations:
    max_scale_version: 23.10.1
    min_scale_version: 22.12.4
    truecharts.org/SCALE-support: "true"
    truecharts.org/category: media
apiVersion: v2
appVersion: 4.5.0
dependencies:
    - name: common
      repository: https://library-charts.truecharts.org
      version: 13.2.2
deprecated: false
description: IRC Highway eBook Downloads.
home: https://truecharts.org/charts/incubator/openbooks
icon: https://truecharts.org/img/hotlink-ok/chart-icons/openbooks.png
keywords:
    - openbooks
    - media
kubeVersion: '>=1.16.0-0'
maintainers:
    - email: info@truecharts.org
      name: TrueCharts
      url: https://truecharts.org
name: openbooks
sources:
    - https://github.com/truecharts/charts/tree/master/charts/incubator/openbooks
    - https://github.com/evan-buss/openbooks
type: application
version: 1.0.4
