annotations:
    max_scale_version: 23.10.1
    min_scale_version: 22.12.4
    truecharts.org/SCALE-support: "true"
    truecharts.org/category: web
apiVersion: v2
appVersion: 2.2.0
dependencies:
    - name: common
      repository: https://library-charts.truecharts.org
      version: 11.1.2
deprecated: false
description: A modern web interface for maintaining Teamspeak3 servers.
home: https://truecharts.org/charts/incubator/ts3-manager
icon: https://truecharts.org/img/hotlink-ok/chart-icons/ts3-manager.png
keywords:
    - ts3-manager
    - teamspeak
    - teamspeak3
kubeVersion: '>=1.16.0-0'
maintainers:
    - email: info@truecharts.org
      name: TrueCharts
      url: https://truecharts.org
name: ts3-manager
sources:
    - https://github.com/truecharts/charts/tree/master/charts/incubator/ts3-manager
    - https://github.com/joni1802/ts3-manager/
type: application
version: 2.0.9
