annotations:
    max_scale_version: 23.10.1
    min_scale_version: 22.12.4
    truecharts.org/SCALE-support: "true"
    truecharts.org/category: media
apiVersion: v2
appVersion: 3.3.10
dependencies:
    - name: common
      repository: https://library-charts.truecharts.org
      version: 14.5.0
description: FlareSolverr is a proxy server to bypass Cloudflare protection
home: https://truecharts.org/charts/stable/flaresolverr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/flaresolverr.png
keywords:
    - flaresolverr
    - proxy
kubeVersion: '>=1.16.0-0'
maintainers:
    - email: info@truecharts.org
      name: TrueCharts
      url: https://truecharts.org
name: flaresolverr
sources:
    - https://github.com/truecharts/charts/tree/master/charts/stable/flaresolverr
    - https://github.com/FlareSolverr/FlareSolverr
version: 10.0.18
