annotations:
    max_scale_version: 23.10.1
    min_scale_version: 22.12.4
    truecharts.org/SCALE-support: "true"
    truecharts.org/category: media
apiVersion: v2
appVersion: "0.6"
dependencies:
    - name: common
      repository: https://library-charts.truecharts.org
      version: 14.3.5
description: Nissan Leaf connected services to MQTT adapter
home: https://truecharts.org/charts/stable/leaf2mqtt
icon: https://truecharts.org/img/hotlink-ok/chart-icons/leaf2mqtt.png
keywords:
    - leaf2mqtt
    - leaf
    - nissan
    - kamereon
    - carwings
kubeVersion: '>=1.16.0-0'
maintainers:
    - email: info@truecharts.org
      name: TrueCharts
      url: https://truecharts.org
name: leaf2mqtt
sources:
    - https://github.com/truecharts/charts/tree/master/charts/stable/leaf2mqtt
    - https://github.com/mitsumaui/leaf2mqtt
    - https://github.com/k8s-at-home/container-images
version: 8.0.9
