annotations:
    truecharts.org/SCALE-support: "true"
    truecharts.org/category: incubator
apiVersion: v2
appVersion: 1.7.3
dependencies:
    - name: common
      repository: https://library-charts.truecharts.org
      version: 14.3.5
deprecated: false
description: Emulatorjs - In browser web based emulation portable to nearly any device for many retro consoles.
home: https://truecharts.org/charts/stable/emulatorjs
icon: https://truecharts.org/img/hotlink-ok/chart-icons/emulatorjs.png
keywords:
    - emulatorjs
kubeVersion: '>=1.16.0-0'
maintainers:
    - email: info@truecharts.org
      name: TrueCharts
      url: https://truecharts.org
name: emulatorjs
sources:
    - https://github.com/truecharts/charts/tree/master/charts/stable/emulatorjs
type: application
version: 6.0.21
