annotations:
    max_scale_version: 23.10.1
    min_scale_version: 22.12.4
    truecharts.org/SCALE-support: "true"
    truecharts.org/category: database
apiVersion: v2
appVersion: latest
dependencies:
    - name: common
      repository: https://library-charts.truecharts.org
      version: 14.3.5
    - condition: mongodb.enabled
      name: mongodb
      repository: https://deps.truecharts.org/
      version: 6.0.67
deprecated: false
description: mongo-express is a web-based MongoDB admin interface written in Node.js, Express.js, and Bootstrap3.
home: https://truecharts.org/charts/stable/mongo-express
icon: https://truecharts.org/img/hotlink-ok/chart-icons/mongo-express.png
keywords:
    - mongo
    - mongodb
    - database
kubeVersion: '>=1.16.0-0'
maintainers:
    - email: info@truecharts.org
      name: TrueCharts
      url: https://truecharts.org
name: mongo-express
sources:
    - https://github.com/truecharts/charts/tree/master/charts/stable/mongo-express
    - https://github.com/mongo-express/mongo-express
type: application
version: 2.0.9
