annotations:
    max_scale_version: 23.10.1
    min_scale_version: 22.12.4
    truecharts.org/SCALE-support: "true"
    truecharts.org/category: MediaServer-Video
apiVersion: v2
appVersion: latest
dependencies:
    - name: common
      repository: https://library-charts.truecharts.org
      version: 11.1.2
deprecated: false
description: Universal Media Server is a DLNA-compliant UPnP Media Server. It is capable of sharing video, audio and images between most modern devices. It was originally based on PS3 Media Server by shagrath, in order to ensure greater stability and file-compatibility.
home: https://truecharts.org/charts/incubator/universal-media-server
icon: https://truecharts.org/img/hotlink-ok/chart-icons/universal-media-server.png
keywords:
    - universal-media-server
    - MediaServer-Video
    - MediaServer-Music
    - MediaServer-Photos
kubeVersion: '>=1.16.0-0'
maintainers:
    - email: info@truecharts.org
      name: TrueCharts
      url: https://truecharts.org
name: universal-media-server
sources:
    - https://github.com/truecharts/charts/tree/master/charts/incubator/universal-media-server
    - https://www.universalmediaserver.com/
type: application
version: 2.0.16
