annotations:
    max_scale_version: 23.10.1
    min_scale_version: 22.12.4
    truecharts.org/SCALE-support: "true"
    truecharts.org/category: media
apiVersion: v2
appVersion: 23.11.2
dependencies:
    - name: common
      repository: https://library-charts.truecharts.org
      version: 14.3.5
deprecated: false
description: tsMuxer is a Transport Stream muxer.
home: https://truecharts.org/charts/stable/tsmuxer
icon: https://truecharts.org/img/hotlink-ok/chart-icons/tsmuxer.png
keywords:
    - media
    - tsmuxer
kubeVersion: '>=1.16.0-0'
maintainers:
    - email: info@truecharts.org
      name: TrueCharts
      url: https://truecharts.org
name: tsmuxer
sources:
    - https://github.com/truecharts/charts/tree/master/charts/stable/tsmuxer
    - https://github.com/jlesage/docker-tsmuxer
type: application
version: 5.0.10
