annotations:
    max_scale_version: 23.10.1
    min_scale_version: 22.12.4
    truecharts.org/SCALE-support: "true"
    truecharts.org/category: media
apiVersion: v2
appVersion: 0.6.9
dependencies:
    - name: common
      repository: https://library-charts.truecharts.org
      version: 11.1.2
description: Self-hosted web tool for generating ambient noises
home: https://truecharts.org/charts/incubator/noisedash
icon: https://truecharts.org/img/hotlink-ok/chart-icons/noisedash.png
keywords:
    - noise
kubeVersion: '>=1.16.0-0'
maintainers:
    - email: info@truecharts.org
      name: TrueCharts
      url: https://truecharts.org
name: noisedash
sources:
    - https://github.com/truecharts/charts/tree/master/charts/incubator/noisedash
    - https://github.com/kaythomas0/noisedash
version: 2.0.12
