annotations:
    max_scale_version: 23.10.1
    min_scale_version: 22.12.4
    truecharts.org/SCALE-support: "true"
    truecharts.org/category: notes
apiVersion: v2
appVersion: latest
dependencies:
    - name: common
      repository: https://library-charts.truecharts.org
      version: 11.1.2
description: BatNoter is a web application that allows users to store notes in their git repository.
home: https://truecharts.org/charts/incubator/batnoter
icon: https://truecharts.org/img/hotlink-ok/chart-icons/batnoter.png
keywords:
    - notes
kubeVersion: '>=1.16.0-0'
maintainers:
    - email: info@truecharts.org
      name: TrueCharts
      url: https://truecharts.org
name: batnoter
sources:
    - https://github.com/truecharts/charts/tree/master/charts/incubator/batnoter
    - https://github.com/batnoter/batnoter
version: 2.0.8
