annotations:
    max_scale_version: 23.10.1
    min_scale_version: 22.12.4
    truecharts.org/SCALE-support: "true"
    truecharts.org/category: media
apiVersion: v2
appVersion: 1.0.16
dependencies:
    - name: common
      repository: https://library-charts.truecharts.org
      version: 14.3.5
description: Expose all events from an Amcrest device to an MQTT broker
home: https://truecharts.org/charts/stable/amcrest2mqtt
icon: https://truecharts.org/img/hotlink-ok/chart-icons/amcrest2mqtt.png
keywords:
    - amcrest2mqtt
kubeVersion: '>=1.16.0-0'
maintainers:
    - email: info@truecharts.org
      name: TrueCharts
      url: https://truecharts.org
name: amcrest2mqtt
sources:
    - https://github.com/truecharts/charts/tree/master/charts/stable/amcrest2mqtt
    - https://github.com/dchesterton/amcrest2mqtt
version: 8.0.9
